### ISSUE TITLE
Booty5 Frozen on Windows 7 and not working over the local network

### ISSUE THREAD

**Issue by sanyaade-iot** [mrmop/Booty5#1]
Hello Mat, I am using Booty5 in my teaching but my students keep getting Booty5 run error message below:

You cannot start application Booty5 from this location because it is already installed from a different location

How can someone resolve this issue?
Why is not possible to run Booty5 at any time?
Does it write to registry or user folder on Windows?
Can it be run standalone non install on Windows for student uses?

Please help!

God blesses!!!

Best regards,
Sanyaade﻿

**Comment by Looserspump** [comment]
like
