### ISSUE TITLE
ReferenceError: FBInstant is not defined

### ISSUE THREAD

**Issue by BracerJack** [mrmop/Booty5#6]
7 May 2020:
This is as barebone as it gets, I just load it, haven't even do anything with it yet and firefox give me that error :-(

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Booty 5</title>
<script src="booty5_min.js"></script>
<script>
window.addEventListener("load", on_init);

function on_init(event)
{
	window.removeEventListener("load", on_init);
	trace ("Hello !");
}

function trace(arg)
{
	console.log(arg);
}
</script>
</head>
<body>

</body>
</html>
```

**Comment by mrmop** [comment]
I've just pushed a fix, let me know how it goes

**Comment by BracerJack** [comment]
I am so happy that you are still supporting the engine !
7 May 2020, booty5_min.js is still giving "ReferenceError: FBInstant is not defined".

I have cleared the cache to make sure it's not using an old version just in case, same error.

**Comment by BracerJack** [comment]
Ok, I redownloaded again hours later to see if it is a github cache issue, nope, issue is still there.

**Comment by mrmop** [comment]
Should be fixed now

**Comment by BracerJack** [comment]
Yes it is fixed thanks !
